persistence true
persistence_location /mosquitto/data/
listener 1883
allow_anonymous false
password_file /mosquitto/auth/passwd
acl_file /mosquitto/config/acl
max_queued_messages 10000
max_inflight_messages 20
log_dest stdout
