"""initial platform schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
revision = 'db9c94423c4d'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dead_letters',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('asset_types',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('asset_id', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'message_id', name='uq_measurement_identity')
    )
    op.create_index('ix_measurement_asset_time', 'measurements', ['project_id', 'asset_id', 'event_time'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('model_artifacts',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('topic', sa.String(length=240), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=True),
    sa.Column('lease_until', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter_versions',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_imports',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rejects', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('signal_mappings',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminals',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topology_revisions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revision_project_interval', 'topology_revisions', ['project_id', 'status', 'valid_from'], unique=False)
    op.create_table('validation_reports',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarms',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('asset_id', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=80), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_states',
    sa.Column('id', sa.String(length=180), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('asset_id', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('voltage_residual', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'message_id', name='uq_state_identity')
    )
    op.create_index('ix_state_run_time', 'component_states', ['run_id', 'asset_id', 'event_time'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('checkpoint', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=True),
    sa.Column('lease_until', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('next_due', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_claim', 'jobs', ['status', 'lease_until', 'next_due'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_state_run_time', table_name='component_states')
    op.drop_table('component_states')
    op.drop_table('alarms')
    op.drop_table('validation_reports')
    op.drop_index('ix_revision_project_interval', table_name='topology_revisions')
    op.drop_table('topology_revisions')
    op.drop_table('terminals')
    op.drop_table('snapshots')
    op.drop_table('signal_mappings')
    op.drop_table('sessions')
    op.drop_table('runs')
    op.drop_table('raw_imports')
    op.drop_table('parameter_versions')
    op.drop_table('outbox')
    op.drop_table('model_artifacts')
    op.drop_table('memberships')
    op.drop_index('ix_measurement_asset_time', table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('data_sources')
    op.drop_table('assets')
    op.drop_table('asset_types')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('dead_letters')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
